{
 "title": "Load test",
 "time": { "from": "2023-02-03T05:53:16.518Z", "to": "2023-02-03T05:54:45.906Z" },
 "panels": [
  {
   "title": "Succesful reqs",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Loadtests_total_successful_requests_made",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Requests",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 6, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "Loadtests_total_failed_requests_made",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "stat",
   "gridPos": { "h": 9, "w": 7, "x": 13, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "Loadtests_current_rps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 9 },
   "targets": [
    { "expr": "Loadtests_current_rps" },
    {
     "expr": "Loadtests_total_failed_requests_made",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency ",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "Loadtests_avg_latency_achieved", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Requests Overtime",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 11, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "Loadtests_total_overall_requests_made",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful/failed reqs over time",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 13, "x": 11, "y": 20 },
   "targets": [
    {
     "expr": "Loadtests_total_successful_requests_made",
     "legendFormat": "__auto"
    },
    {
     "expr": "Loadtests_total_failed_requests_made",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}